const data = {
  products: [
    {
      name: 'Free shirt',
      slug: 'Free shirt nicki',
      category: 'Shirts',
      image: '/images/alex-haigh-fEt6Wd4t4j0-unsplash.jpg',
      price: 70,
      brand: 'Nike',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free shirt',
      slug: 'Free shirt shiva',
      category: 'Shirts',
      image: '/images/benjamin-rascoe-WdhmRPvMn7A-unsplash.jpg',
      price: 70,
      brand: 'Nike',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free shirt',
      slug: 'Free shirt arsham',
      category: 'Shirts',
      image: '/images/ihor-rapita-F3um9jkcCZY-unsplash.jpg',
      price: 70,
      brand: 'Nike',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free shirt',
      slug: 'Free ',
      category: 'Shirts',
      image: '/images/mohamad-khosravi-4fkUAduhoSY-unsplash.jpg',
      price: 70,
      brand: 'Nike',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free shirt',
      slug: 'Free shirts',
      category: 'Shirts',
      image: '/images/nimble-made-hMMXhKSZk7k-unsplash.jpg',
      price: 70,
      brand: 'Nike',
      rating: 8,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
};

export default data;
